backend:
  name: git-gateway
  branch: master
media_folder: "static/images"
public_folder: "images"
collections:
  - name: "pages"
    label: "pages"
    files:
      - file: "content/_index.md"
        label: "Home page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Surname", name: "surname", widget: "string" }
          - label: "First Section" 
            name: "first_section"
            widget: "object"
            fields: 
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Button", name: "button", widget: "string"}
          - label: "Second Section" 
            name: "second_section"
            widget: "object"
            fields: 
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Button", name: "button", widget: "string"}
              - {label: "Background Image", name: "background_image", widget: "image"}
          - label: "Third Section" 
            name: "third_section"
            widget: "object"
            fields: 
              - label: "Cards"
                name: "title"
                widget: "List"
                allow_add: true
                fields:
                  - {label: "Line 0", name: "line_0", widget: "string"}
                  - {label: "Line 1", name: "line_1", widget: "string"}
                  - {label: "Line 2", name: "line_2", widget: "string"}
          - label: "Fourth Section" 
            name: "fourth_section"
            widget: "object"
            fields: 
              - {label: "Text", name: "text", widget: "string"}
